# .travis.yml

dist: xenial

language: python

cache: pip

python:
    - "3.8"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - pip install requirements.txt

script:
    - pytthon unittests.py