# .travis.yml
sudo: false

language: python

cache: pip

python:
    - "3.7"

install:
    - pip install -r requirements.txt

script:
    - python tests/test_sampling.py
    - python tests/test_features.py
