# .travis.yml
sudo: false

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install git+https://github.com/smba/pycosa.git@main

install:
    - pip install -r requirements.txt

script:
    - python tests/test_sampling.py
    - python tests/test_features.py

after_success:
  - codecov
